version: '2'

volumes:
  sq_db_data:

services:

  sonarqube:
    restart: always
    image: sonarqube:${SQ_VERSION}
    environment:
      SONARQUBE_JDBC_USERNAME: ${SQ_JDBC_USER} 
      SONARQUBE_JDBC_PASSWORD: ${SQ_JDBC_PASSW} 
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonar-postgres:5432/sonar
    depends_on: sonar-postgres
    
  sonar-postgres:
    restart: always
    image: postgres:${PG_VERSION}
    build: sq-db
    environment:
      POSTGRES_USER: ${SQ_JDBC_USER} 
      POSTGRES_PASSWORD: ${SQ_JDBC_PASSW} 
    volumes:
      - sq_db_data:/var/lib/postgresql/data

