version: '2'

volumes:
  sq_db_data:

services:

  sonarqube:
    restart: always
    image: sonarqube:5.6
    environment:
      SONARQUBE_JDBC_USERNAME: ${SQ_JDBC_USER} 
      SONARQUBE_JDBC_PASSWORD: ${SQ_JDBC_PASSW} 
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonar-postgres:5432/sonar
    depends_on: 
      - sonar-postgres
    ports:
      - ${SQ_PORT_EXTERN}:${SQ_PORT_INTERN}
    
  sonar-postgres:
    restart: always
    build: sq-db
    image: postgres:9.5
    environment:
      POSTGRES_USER: ${SQ_JDBC_USER} 
      POSTGRES_PASSWORD: ${SQ_JDBC_PASSW} 
    volumes:
      - sq_db_data:/var/lib/postgresql/data

